language: smalltalk
sudo: false

addons:
  apt:
    packages:
    - mongodb-org-server

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-6.0
  - Pharo-5.0

# configuration
before_script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'carog-ci@travis-ci.org'
