language: smalltalk
sudo: false

addons:
  apt:
    packages:
    - mongodb-org-server

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-6.0
  - Pharo-5.0
