language: smalltalk
sudo: false

addons:
  apt:
    packages:
    - mongodb-org-server

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-6.0
#  - Pharo-5.0 (disabled because 2 tests fail: ExternalData(Object)>>doesNotUnderstand: #readStringUTF8. Pb coming from Iceberg)

# configuration
before_script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'cargo-ci@travis-ci.org'
